name: CD - Mirror

on:
  push:
    branches: [main]

env:
  MIRROR_REPO_URL: "git@github.com:EpitechPGE3-2026/G-SVR-500-BDX-5-1-survivor-4.git"

jobs:
  mirror:
    if: github.repository != 'EpitechPGE3-2026/G-SVR-500-BDX-5-1-survivor-4'

    runs-on: ${{ vars.RUNNER }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout (mirror complet)
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Mirror Repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_REPO_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
